# Generated by Django 3.1.1 on 2020-09-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hello',
            old_name='tools',
            new_name='slug',
        ),
    ]
